name: Docker

on:
  push:
    # Publish `master` as Docker `latest` image.
    branches:
      - master

    # Publish `v1.2.3` tags as releases.
    tags:
      - v*

  # Run tests for any PRs.
  pull_request:

env:
  # TODO: Change variable to your image's name.
  IMAGE_NAME: deepmd-kit
  VERSION: 3.0.2

jobs:
  # Run tests.
  # See also https://docs.docker.com/docker-hub/builds/automated-testing/
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - VARIANT: cpu
            BASE_IMAGE: ubuntu:jammy
          - VARIANT: cuda128
            BASE_IMAGE: ubuntu:jammy
          
    env: 
      VARIANT: ${{ matrix.VARIANT }}
      BASE_IMAGE: ${{ matrix.BASE_IMAGE }}

    steps:
      - name: Delete huge unnecessary tools folder
        run: rm -rf /opt/hostedtoolcache
      - uses: actions/checkout@v2

      - name: Run tests
        run: |
          docker build --build-arg VARIANT=$VARIANT --build-arg VERSION=$VERSION --build-arg BASE_IMAGE=$BASE_IMAGE --file $IMAGE_NAME/Dockerfile -t ghcr.io/deepmodeling/${IMAGE_NAME}:${VERSION}_${VARIANT} -t deepmodeling/${IMAGE_NAME}:${VERSION}_${VARIANT} .

      - name: Log into GitHub Container Registry
        run: echo "${{ secrets.CR_PAT }}" | docker login https://ghcr.io -u ${{ github.actor }} --password-stdin
        if: github.event_name == 'push'

      - name: Push image to GitHub Container Registry
        run: docker push ghcr.io/deepmodeling/${IMAGE_NAME}:${VERSION}_${VARIANT}
        if: github.event_name == 'push'

      - name: Log into Dockerhub
        run: echo "${{ secrets.DOCKER_TOKEN }}" | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
        if: github.event_name == 'push'

      - name: Push image to Dockerhub
        run: docker push deepmodeling/${IMAGE_NAME}:${VERSION}_${VARIANT}
        if: github.event_name == 'push'
